allow-lan: false
bind-address: "*"
mode: rule
geodata-mode: true
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
secret: ''
external-ui: ./ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
keep-alive-interval: 15
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
  enhanced-mode: redir-host
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - URLTest
      - Selector
  - name: URLTest
    type: url-test
    use:
      - ChinaG
    url: 'http://www.google.com/generate_204'
    interval: 3600
  - name: Selector
    type: select
    use:
      - ChinaG
proxy-providers:
  ChinaG:
    type: http
    url: "clash订阅地址"
    interval: 3600
    path: ./providers/ChinaG.yaml
    filter: "(I|H)[.]|(I|H)+[.]"
    health-check:
      enable: true
      interval: 3600
      url: 'http://www.google.com/generate_204'
rule-providers:
  amaury:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Amaury-GitHub/ClashRule/main/amaury.txt"
    path: ./providers/amaury.yaml
    interval: 3600
  cn:
    type: http
    behavior: domain
    path: ./providers/cn_domain.yaml
    url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/cn_domain.yaml"
    interval: 3600
rules:
  - RULE-SET,amaury,DIRECT
  - DOMAIN-KEYWORD,google,PROXY
  - RULE-SET,cn,DIRECT
  - GEOSITE,category-ads-all,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,twitter,PROXY
  - GEOSITE,pixiv,PROXY
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,biliintl,PROXY
  - GEOSITE,onedrive,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,PROXY
  - GEOIP,CN,DIRECT
  - DST-PORT,443,PROXY
  - MATCH,DIRECT